# Generated by Django 4.2.3 on 2025-08-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_sin_subsidio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
